# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    auto-rebase:
        name: AutoRebase
        runs-on: ubuntu-latest
        steps:
            - uses: Label305/AutoRebase@v0.1
              with:
                  # We can't use the built-in secrets.GITHUB_TOKEN yet because of this limitation:
                  # https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676
                  # In the meantime, use a token granting write access on the repo:
                  # - a GitHub App token
                  #   See https://github.com/marketplace/actions/github-app-token.
                  # - a personal access token
                  #   See https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line.
                  github_token: ${{ secrets.AUTOREBASE_TOKEN }}

